-- Seed data: the live project rows exported (read-only) from the previous
-- managed Supabase database on 2026-09-25 before cutover.
-- source_rows: 8
-- thumbnails/screenshots: none (no Supabase Storage URLs existed in the data)

insert into public.projects
  (id, slug, title, short, platforms, capabilities, industries, tags, access,
   thumbnail_url, screenshots, model_url, challenge, approach, value,
   priority, featured, is_template, public_enabled, created_at, updated_at)
values
  ('00eec715-3cb0-40b9-b428-49b7e1d2be6d',
   '13-week-cash-flow-liquidity-model',
   '13-Week Cash Flow & Liquidity Model',
   'Rolling liquidity visibility, working capital and scenario analysis.',
   '{"Excel"}',
   '{"Working Capital","Cash Flow","FP&A"}',
   '{"General / Cross-industry"}',
   '{"Cash Forecasting","DSO / DOH / DPO","Scenarios"}',
   'interactive',
   null,
   '{}',
   null,
   'Give management a forward-looking view of cash, working capital pressure and liquidity risk.',
   'A rolling 13-week model combining actuals, forecast vintages, cash bridge, EBITDA-to-cash reconciliation and working-capital drivers.',
   'Improves liquidity visibility, highlights working-capital pressure early and gives management a clearer basis for cash decisions.',
   100,
   true,
   true,
   true, now(), now()),

  ('5656351e-f63e-46dc-8e95-66cd07d84604',
   'management-accounts-executive-reporting',
   'Management Accounts & Executive Reporting',
   'P&L, balance sheet, KPIs and management decision support.',
   '{"Excel"}',
   '{"Management Reporting","FP&A","Dashboards"}',
   '{"Multi-location Retail","F&B"}',
   '{"Management Accounts","KPI Pack","MTD / YTD"}',
   'interactive',
   null,
   '{}',
   null,
   'Turn monthly financial data into a concise management view of performance, variances and operational drivers.',
   'A management reporting pack combining financial statements, KPIs, commentary and visual analysis for executive review.',
   'Turns month-end data into a concise management view of performance, variances and operating priorities.',
   90,
   true,
   true,
   true, now(), now()),

  ('52d6062f-cf13-4c41-aec9-2fb79d86bb7e',
   'multi-location-retail-fp-a',
   'Multi-Location Retail FP&A',
   'Store, country and format-level performance analysis.',
   '{"Excel","Power BI"}',
   '{"FP&A","Management Reporting","Dashboards"}',
   '{"Multi-location Retail"}',
   '{"Retail FP&A","Store Economics","L2L"}',
   'interactive',
   null,
   '{}',
   null,
   'Understand performance across stores, formats and markets without losing sight of the drivers behind the consolidated result.',
   'A multi-location planning and analysis model with store lifecycle, format, country, P&L and operating KPI views.',
   'Makes it easier to identify where performance is being created or lost across stores, formats and markets.',
   80,
   true,
   true,
   true, now(), now()),

  ('3d4f3d2c-4594-4a64-a29d-2287caa3d43c',
   'budget-forecast-model',
   'Budget & Forecast Model',
   'Driver-based planning, scenarios and variance analysis.',
   '{"Excel"}',
   '{"FP&A"}',
   '{"General / Cross-industry","SaaS"}',
   '{"Budgeting","Forecasting","Sensitivity"}',
   'preview',
   null,
   '{}',
   null,
   'Create a planning model that can be updated quickly as assumptions change.',
   'A driver-based forecast structure linking operational assumptions to financial outcomes, scenarios and variance analysis.',
   'Creates a faster, more transparent planning cycle with clear links between assumptions and financial outcomes.',
   70,
   false,
   true,
   true, now(), now()),

  ('65d6691d-70f1-4c7e-9fb0-e268530344f5',
   'acquisition-lbo-model',
   'Acquisition & LBO Model',
   'Transaction analysis, debt structure and returns.',
   '{"Excel"}',
   '{"Corporate Finance","Valuation"}',
   '{"General / Cross-industry"}',
   '{"M&A","LBO","Returns"}',
   'request',
   null,
   '{}',
   null,
   'Evaluate an acquisition under different operating, financing and exit assumptions.',
   'An integrated acquisition/LBO framework covering purchase price, debt, operating performance, cash flow, exit and investor returns.',
   'Supports disciplined transaction decisions by making financing, operating and exit assumptions transparent.',
   60,
   false,
   true,
   true, now(), now()),

  ('6e54b3b8-beb8-405d-af30-e9ff096b26ba',
   'valuation-investment-appraisal',
   'Valuation & Investment Appraisal',
   'DCF, comparables and decision-focused sensitivity analysis.',
   '{"Excel"}',
   '{"Valuation","Corporate Finance"}',
   '{"General / Cross-industry","SaaS"}',
   '{"DCF","NPV / IRR","Valuation"}',
   'preview',
   null,
   '{}',
   null,
   'Translate forecasts and risk assumptions into an informed investment decision.',
   'Valuation and investment appraisal using DCF, scenario/sensitivity analysis and return metrics.',
   'Frames investment decisions around value, risk, sensitivity and expected returns.',
   50,
   false,
   true,
   true, now(), now()),

  ('5d9bf76e-fb68-4e4c-ab13-8a821febaa90',
   'cfo-executive-dashboards',
   'CFO & Executive Dashboards',
   'Financial and operational visibility at a glance.',
   '{"Power BI","Excel"}',
   '{"Dashboards","Management Reporting","Working Capital"}',
   '{"General / Cross-industry","Multi-location Retail"}',
   '{"Power BI","KPIs","Executive Reporting"}',
   'interactive',
   null,
   '{}',
   null,
   'Give leadership fast visibility of the few measures that matter most.',
   'Decision-focused dashboards combining profitability, cash, working capital, trends, variances and operating KPIs.',
   'Gives executives a faster view of performance and the drivers requiring management attention.',
   40,
   false,
   true,
   true, now(), now()),

  ('1bda0f86-3f09-4c1d-ab88-c9e945d153a8',
   'cfo-fp-a-capability-pack',
   'CFO & FP&A Capability Pack',
   'Executive overview of finance capabilities and selected work.',
   '{"PDF"}',
   '{"FP&A","Management Reporting","Corporate Finance"}',
   '{"General / Cross-industry"}',
   '{"CFO Advisory","FP&A","Credentials"}',
   'preview',
   null,
   '{}',
   null,
   'Help a prospective client quickly understand the breadth and depth of finance support available.',
   'A concise capability pack covering reporting, forecasting, cash, performance, corporate finance, dashboards, credentials and selected case studies.',
   'Lets prospective clients assess the breadth of CFO and FP&A support in one concise executive document.',
   0,
   false,
   true,
   true, now(), now())
on conflict (id) do nothing;
